# Generated by Django 3.0.10 on 2020-11-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='fat_percentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fat percentage'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (3, 'Neutral')], null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='lenght_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='user',
            name='prefered_units',
            field=models.IntegerField(choices=[(0, 'Kilograms / centimeter'), (1, 'Pounds / Inches')], default=0, verbose_name='Prefered units'),
        ),
        migrations.AddField(
            model_name='user',
            name='prefix',
            field=models.CharField(blank=True, max_length=15, verbose_name='Prefix'),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=45, verbose_name='Surname'),
        ),
        migrations.AddField(
            model_name='user',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Name'),
        ),
    ]
