# Generated by Django 3.0.10 on 2020-11-14 20:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatpercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Upload date')),
                ('weight', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(500.0)], verbose_name='Weight')),
                ('measurement_type', models.IntegerField(blank=True, choices=[(0, 'Jackson/Pollock 3'), (1, 'Jackson/Pollock 4'), (2, 'Jackson/Pollock 7'), (3, 'Durrin/Womersley'), (4, 'Digital measurement')], null=True, verbose_name='Measurement Type')),
                ('chest_mm', models.IntegerField(blank=True, null=True, verbose_name='Chest measurement in mm')),
                ('abdominal_mm', models.IntegerField(blank=True, null=True, verbose_name='Abdominal measurement in mm')),
                ('thigh_mm', models.IntegerField(blank=True, null=True, verbose_name='Thigh measurement in mm')),
                ('tricep_mm', models.IntegerField(blank=True, null=True, verbose_name='Tricep measurement in mm')),
                ('suprailiac_mm', models.IntegerField(blank=True, null=True, verbose_name='Suprailiac measurement in mm')),
                ('axilla_mm', models.IntegerField(blank=True, null=True, verbose_name='Axilla measurement in mm')),
                ('subscapular_mm', models.IntegerField(blank=True, null=True, verbose_name='Subscapular measurement in mm')),
                ('bicep_mm', models.IntegerField(blank=True, null=True, verbose_name='Bicep measurement in mm')),
                ('percentage', models.FloatField(blank=True, null=True, verbose_name='percentage')),
                ('lean_body_mass', models.FloatField(blank=True, null=True, verbose_name='Lean body mass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatpercentage', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
