# Generated by Django 3.0.10 on 2020-11-15 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0001_initial'),
        ('fatpercentage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatpercentage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatpercentage', to='athlete.Athelete', verbose_name='User'),
        ),
    ]
