# Generated by Django 3.0.10 on 2020-11-15 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Name')),
                ('prefix', models.CharField(blank=True, max_length=15, verbose_name='Prefix')),
                ('surname', models.CharField(blank=True, max_length=45, verbose_name='Surname')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('biological_sex', models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], null=True, verbose_name='Biological sex')),
                ('lenght_cm', models.FloatField(blank=True, null=True, verbose_name='Length')),
                ('weight_kg', models.FloatField(blank=True, null=True, verbose_name='Weight')),
                ('fat_percentage', models.IntegerField(blank=True, null=True, verbose_name='Fat percentage')),
                ('prefered_units', models.IntegerField(choices=[(0, 'Kilograms / centimeter'), (1, 'Pounds / Inches')], default=0, verbose_name='Prefered units')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Athelete')),
            ],
        ),
    ]
